### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by ianm1837** [F4R4N/movie-quote#10]
Hello,

I was starting to use this API for a class project when it suddenly went down yesterday. 

I was able to get this hosted on my own development server, but there is no data included in this repo. Is that something that you could share?

I'm also very interested in Dockerizing this.

If you would like I would be willing to update installation instructions for future users as well.

Thanks!

**Comment by iridium951** [comment]
Same issue. This API is already in use in my project, but is no longer working. 

This goes for both https://movie-quote-api.herokuapp.com/ and https://swquote.herokuapp.com/. 

Any update would be greatly appreciated, thank you!

**Comment by F4R4N** [comment]
sorry for the inconvenience,
Heroku started to charge for the Heroku Postgres dyno, and its no longer free. so basically the application can't access the data stored in the database, which causes the error. I don't have access to the data, I should call Heroku support for that, unfortunately.
probably that's why the wsquote is also down.

**Comment by F4R4N** [comment]
I can't fix it until I find a new free hosting platform.

**Comment by iridium951** [comment]
Ah well, understandable. Thank you for letting us know!

**Comment by vanowm** [comment]
Please update the readme, so people won't waste their time with at the moment useless repository.
