### ISSUE TITLE
Integrity error

### ISSUE THREAD

**Issue by Ayeven** [F4R4N/movie-quote#6]
Tried the going to [v1/quote](https://movie-quote-api.herokuapp.com/v1/quote/) and gotten `Integrity error`
- Full error : [Source bin](https://sourceb.in/1u4cdYVHmA)

**Comment by F4R4N** [comment]
hi there, thanks for reporting this.
I don't get the exception now, do you still have the same problem?

**Comment by Ayeven** [comment]
Looking good 👍

**Comment by F4R4N** [comment]
I think this was because of timezone differences. probably date in your time zone was 2021/07/10 but the server timezone (UTC) was 2021/07/11, the app tried to create a new object for the date 2021/07/10 but it already exists and also the field is unique, and the exception raise like that. sorry about that.

I disable timezone to fix this bug at #7
